### ISSUE TITLE
Observed Errors in Solutions in d06 & d07

### ISSUE THREAD

**Issue by mstites** [zdelrosario/evc-course#10]
While going through excercises d06 and d07 I had noticed a few issues in reference to the solutions:

1. d06 Data:  Deriving Quantities - The answer showed up on my copy of the downloaded course files for q4 and q5.
2. d07 Vis: Histograms - q4 doesn't have a solution.

**Comment by zdelrosario** [comment]
Thanks for the feedback! Addressed in commit 4c566da
