### ISSUE TITLE
Makefile: Incomplete 'make clean' command and 'make pdf' tweak

### ISSUE THREAD

**Issue by cstakeda** [zdelrosario/evc-course#4]
In [Makefile](https://github.com/zdelrosario/evc-course/blob/main/Makefile):
1. Calling `make clean` doesn't have a `cd challenges_assignment; make clean` call to remove assignments created from the challenge master
2. `make clean` in challenges_assignment, exercises_assignment, and exercises_solution does not remove the generated "images" folder
3. `make pdf` does not have a 'main' call before calling `jb build` which would enable changes between Makefile commands to not be presented in the pdf

**Comment by zdelrosario** [comment]
1 and 3 resolved by [d9ee477](https://github.com/zdelrosario/evc-course/commit/d9ee4770c643da3b3ec9cd6ab1e621e17a8a53a5); clearing the images folder doesn't seem as important to me. The assignment files should update, but image files will remain relatively static.
