### ISSUE TITLE
Issues with `d02-e-data01-isolate-assignment`

### ISSUE THREAD

**Issue by Emma-Fox** [zdelrosario/evc-course#9]
- Directly above q2, the explanation of `tf_` states that it "`tr`ansforms" data; should this be changed to "`t`rans`f`orms" to highlight the correct letters?
 - typo: under "Column Selection", change "datset" -> "dataset"
 - typo: under "Accessing Column Values", "Note that returns a different datatype" is missing a word
 - I was confused by the syntax in q9 - I tried to use `or` statements, but when those didn't work, I had to check the solution to get `|`. I remember those symbols meaning the same thing, so why doesn't `or` work here?

**Comment by zdelrosario** [comment]
Thanks for the feedback! I addressed these comments in [ab74aba](https://github.com/zdelrosario/evc-course/commit/ab74aba1180af7e7dddd038f560efc70dd29470f).

Note that the `|` operator is overloaded for `DF`, but I'm unaware of a way to overload the `or` keyword. I added a note about this inside the exercise.
